### PR TITLE
Ender IO

### PR DESCRIPTION
**Pull request by HenryLoenwind**
Not yet complete, but at least our beta testers will see something else but error messages ;)

### CODE REVIEW

**Comment by brandon3055** [comment]
Nice! First mod not documented by me! 
Thoughts on the editor? I know it needs a lot of work. My plan is to completely re write it using javafx.

**Comment by HenryLoenwind** [comment]
The editor actually is fine. I only have some minor points:

* I didn't find the Edit>Format menus for ages, A format dropdown-button above the editor may be better.
* The editor window's wordwrap sometimes is off randomly.
* After renaming a page, the the page tree switched itself to "Windows" (yellow folders, +-buttons)
* I had to create the two en_us folders and the "machines" folder manually in the file system.

The rest of my issues are with the in-game viewer:

image
weird whitespace in lines and early line breaks

image
Some items have a black line on the left when sized to 9 (half size). They are ok at 8.

In any case, item stacks sit a bit low when used in text.

image
It would be nice to blacklist some JEI categories, e.g. the "Description" category, or our "charge item" category.

image
When recipes are "word-wrapped", recipes on first line and following ones have a different left indent. (I haven't playing with formatting here, but I'd expect the default to look nice ;) )

**Comment by brandon3055** [comment]
The issue with crafting categories is something i'm planning to address. The other issues are new to me. Sounds like i still have a few issues to figure out.

**Comment by HenryLoenwind** [comment]
PS: Found another one: The help for Content Relations says they are not implemented yet. Seems I have to go through all pages and add the stacks a 4th time (icon, §stack, §recipe, relation)...

**Comment by brandon3055** [comment]
Yea content relations are implemented. And one of the main things i want to implement when i do the re write is just a lot of ease of use changes. Little things like making it possible just copy a stack and paste it into the icons or relations lists.

**Pull request merged**
