### PR TITLE
Traveller's Backpack Docs

### PR DESCRIPTION
**Pull request by Backcheck21**
Added Traveller's Backpack documentation. https://github.com/Tiviacz1337/Travellers-Backpack
Planning on doing more mods in the future.

### CODE REVIEW

**Comment by brandon3055** [comment]
I don't see any reason not to pull this. 
But this can not be marked as verified until @Tiviacz1337 reviews it and gives the ok.

This process will be semi automated eventually but for now everything has to go through me.

**Comment by Tiviacz1337** [comment]
May I know what is it by the way?

**Comment by brandon3055** [comment]
This is my attempt at building a community driven documentation mod for minecraft. There are a lot more details on the curse page.
https://www.curseforge.com/minecraft/mc-mods/project-intelligence

**Comment by Tiviacz1337** [comment]
That's cool, I accept this doc 👍

**Pull request merged**
