### PR TITLE
Upload Chinese translation (partial)

### PR DESCRIPTION
**Pull request by baka-gourd**
Upload Chinese translation.
The mod can't detect file path under linux.(eg. ~/home/<name>/PI-Docs/...)
:p

### CODE REVIEW

**Comment by brandon3055** [comment]
I can tell you just copy-pasted and updated the files on disk. That caused a few issues i had to fix.
I would recommend you use the built in editor but it still needs a bit of work to fix multi language support so you may run into some issues.

**Comment by baka-gourd** [comment]
> I can tell you just copy-pasted and updated the files on disk. That caused a few issues i had to fix.
> I would recommend you use the built in editor but it still needs a bit of work to fix multi language support so you may run into some issues.

Yes, I am sorry. But I have encountered an irreparable problem: mod does not recognize my file path. So I can only copy-paste and updated the files on disk. We would love to have a great editor.
Maybe a bug:


I can't open edit mode. (maybe I should use windows :P). The Chinese path in the picture was changed to English and an error occurred.
**Should I submit a issues?**
My English is not very good, please forgive me.

**Comment by brandon3055** [comment]
That file path looks... unusual. What OS are you using? 
You need to use an absolute file path and you will also need to add \ModDocs to the end

**Comment by baka-gourd** [comment]
> 该文件路径看起来......不寻常。你用的是什么操作系统？
> 您需要使用绝对文件路径，并且还需要将\ ModDocs添加到最后

I am using linux (ubuntu18.04): P
I found the reason: I should‘t add ~/
**The correct one should be: /xxx/.../xxx/PI-Docs/ModDocs**
**The error is: ~/xxx/.../xxx/PI-Docs/ModDocs**
Thank you!

**Pull request merged**
