### PR TITLE
Add enderio translate(zh_cn)

### PR DESCRIPTION
**Pull request by baka-gourd**
Add enderio translate.

### CODE REVIEW

**Comment by baka-gourd** [comment]
@brandon3055 :relaxed:

**Comment by baka-gourd** [comment]
@brandon3055

**Comment by baka-gourd** [comment]
@brandon3055

**Comment by brandon3055** [comment]
Sorry for the delay. As this PR contains changes that effect mods that are not my own i would like @HenryLoenwind or someone else from the ender IO team to review them before i merge this PR.

**Comment by HenryLoenwind** [comment]
I don't read Chinese, so I can not really look at it properly. It only adds a Chinese translation, not changing the original, so I'd say it's fine.

**Comment by baka-gourd** [comment]
> I don't read Chinese, so I can not really look at it properly. It only adds a Chinese translation, not changing the original, so I'd say it's fine.

Yes, I know that. I have checked it several times before submitting.
I think it's not very good to insert small images in the document (like the icon of the ether wrench), which may affect reading.
And perhaps should [this](https://github.com/SleepyTrousers/EnderIO/pull/4839) be combined to update the mod translation?

**Comment by brandon3055** [comment]
@HenryLoenwind I'm pretty much the same way with my localisations. But given the nature of PI i want to get the OK from the developer of a mod before i pull changes. This process will be a lot easier if @covers1624 ever gets around to finishing PiBot.

**Comment by HenryLoenwind** [comment]
sure and I appreciate it. I now turned notifications for this repo on so I'll notice it in the future without being pinged.

**Pull request merged**
