### PR TITLE
Updated for DA 1.7.0 and Fixed Draconic SOP

### PR DESCRIPTION
**Pull request by FoxMcloud5655**
Updated Draconic Additions documentation to 1.7.0 and fixed missed words in Draconic Staff of Power.

### CODE REVIEW

**Comment by brandon3055** [comment]
Why were both the structure files missing the "verified" field? Please dont touch that.
If @covers1624 ever gets around to finishing PI Bot PR's that modify the verified field in this way will be automatically rejected.

**Comment by FoxMcloud5655** [comment]
I did not touch those files in any way.  That's how PI edited it.

**Comment by brandon3055** [comment]
Not exactly sure how that's possible... PI is incapable of writing that file without those flags... 
What version of PI are you using?

**Comment by FoxMcloud5655** [comment]
I'll have to get back to you on that one when I have access to my computer again...  I assure you that I did not change the file manually.

I do want to note, however, that I was creating completely new documentation for the new version of my mod, if that helps.

**Comment by FoxMcloud5655** [comment]
It is 1.0.1.8.

Here's a GIF of the process and it not updating the structure file's verified fields.


PI

**Comment by brandon3055** [comment]
Umm.... wat?
Did you get that from maven or something? Because that's older than even the initial curse release....  
I suggest you update...

**Comment by FoxMcloud5655** [comment]
It is?!  Yes, it is from maven, and is the version that DE requests on GitHub.

This won't happen again, sorry.

**Comment by brandon3055** [comment]
No problem. Just remember the version a mod depends on is the oldest version that mod will work with. Which is not necessarily the version you should be using.

**Comment by FoxMcloud5655** [comment]
Didn't know that; thank you for the tip.  Sorry, DA is literally the first mod I've ever created.

**Pull request merged**
